import APIUser from '../users/APIUser';
import type { APIMapClaim } from './APIMapClaim';
import type { APIMapEffectType } from './APIMapEffectType';

export type APIMap = {
    id: number;
    mapset: number;
    mappers: APIUser[];
    hash: string;
    difficulty: string;
    title: string;
    artist: string;
    source: string;
    tags: string;
    mode: number;
    status: number;
    bpm: number;
    length: number;
    notes: number;
    'long-notes': number;
    maxcombo: number;
    nps: number;
    rating: number;
    accuracy: number;
    health: number;
    effects: APIMapEffectType;
    has_voted_rate: boolean;
    claim_owned?: APIMapClaim;
    claim_your_club?: APIMapClaim;
};
